### ISSUE TITLE
[Issue]: How does one build rocm-examples/HIP-Basic/assembly_to_executable for Windows?

### ISSUE THREAD

**Issue by ButchAnton** [amd/rocm-examples#101]
### Problem Description

I have installed HIP/ROCm 5.7.1 for Windows on Windows 10.  I have also installed make for Windows using winget.  However, I cannot build the assembly_to_executable example code under Windows 10.  I have tried modifying the Makefile to address the Windows-specific paths, etc.  I have also changed it to use hip_obj_gen_win.mcin.  However, even with these changes, it does not build cleanly.  The last error I received was the linker complaining that the format of main_device.o was unknown.

I have compiled the unchanged example code under Ubunto 22.04 and it builds and runs perfectly.

Can someone please provide the changes needed to build and run this example under Windows 10?

Thank you!

### Operating System

Windows 10

### CPU

AMD Threadripper with dual AMD graphics cards (6800 & 7900)

### GPU

AMD Radeon Pro W6800, AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 5.7.1

**Comment by Snektron** [comment]
Hi, the Makefiles are mainly intended for Linux. If you want to figure out exactly what is going on on Windows, I suggest building using cmake with ninja as generator (`-GNinja`), and then using `ninja -nv` to make ninja print out the commands that its executing. Based on this info on my end, you might have to change occurences of `host-x86_64-unknown-linux-gnu` to `host-x86_64-pc-windows-msvc`.

**Comment by ButchAnton** [comment]
Hi, @Snektron!  Thank you for your reply.  I was able to get it to work by changing the -triple argument to "x86_64-pc-windows-msvc".  Where are these documented?

**Comment by Snektron** [comment]
As described in the readme of the assembly_to_executable example, the offload bundle requires an empty entry for the host. This takes the form of `host-<isa>-<vendor>-<os>-<abi>` specialized for the target that you want the final binary to run on. For linux this is `host-x86_64-unknown-linux-gnu`, and for windows `host-x86_64-pc-windows-msvc`. Exactly how this works with the offload bundler is described on the [clang offload bundler documentation page](https://clang.llvm.org/docs/ClangOffloadBundler.html#id8). This combination of parameters is generally called a target triple, and its documented on the [clang cross compilation documentation page](https://clang.llvm.org/docs/CrossCompilation.html#target-triple).
