### ISSUE TITLE
[Issue]: CMake configuration fails with rocm 6.1

### ISSUE THREAD

**Issue by kuhar** [amd/rocm-examples#108]
### Problem Description

I did a fresh install of Ubuntu 22.04 and rocm 6.1 and can't build the samples. The error message is:
```
➜  build git:(develop) cmake .. -GNinja
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The HIP compiler identification is Clang 17.0.0
-- Detecting HIP compiler ABI info
-- Detecting HIP compiler ABI info - done
-- Check for working HIP compiler: /opt/rocm-6.1.0/llvm/bin/clang++ - skipped
-- Detecting HIP compile features
-- Detecting HIP compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- GPU_ARCHITECTURES: gfx1100
-- GPU_ARCHITECTURES: gfx1100
CMake Error at HIP-Basic/llvm_ir_to_executable/CMakeLists.txt:65 (find_program):
  Could not find LLVM_DIS_COMMAND using the following names: llvm-dis
```

There's no `llvm-dis` under `/opt/rocm`, so I'm not sure where cmake is expecting to find one.
```
➜  build git:(develop) find /opt/rocm/ -name 'llvm-*'
/opt/rocm/lib/llvm/bin/llvm-objcopy
/opt/rocm/lib/llvm/bin/llvm-dwarfdump
/opt/rocm/lib/llvm/bin/llvm-strip
/opt/rocm/lib/llvm/bin/llvm-objdump
/opt/rocm/lib/llvm/bin/llvm-mc
/opt/rocm/lib/llvm/bin/llvm-otool
/opt/rocm/lib/llvm/bin/llvm-readobj
/opt/rocm/lib/llvm/bin/llvm-readelf
/opt/rocm/lib/llvm/bin/llvm-bitcode-strip
/opt/rocm/lib/llvm/bin/llvm-ranlib
/opt/rocm/lib/llvm/bin/llvm-link
/opt/rocm/lib/llvm/bin/llvm-install-name-tool
/opt/rocm/lib/llvm/bin/llvm-ar
/opt/rocm/lib/llvm/share/man1/llvm-mc.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-objcopy.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-strip.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-readelf.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-ar.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-objdump.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-ranlib.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-dwarfdump.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-readobj.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-link.1.gz
/opt/rocm/lib/llvm/share/man1/llvm-otool.1.gz
```

### Operating System

Ubuntu 22.04.4

### CPU

AMD Ryzen 9 7950X

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.1.0

### Additional Information

```
  echo "OS:" && cat /etc/os-release | grep -E "^(NAME=|VERSION=)";
  echo "CPU: " && cat /proc/cpuinfo | grep "model name" | sort --unique;
  echo "GPU:" && /opt/rocm/bin/rocminfo | grep -E "^\s*(Name|Marketing Name)";
OS:
NAME="Ubuntu"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
CPU: 
model name	: AMD Ryzen 9 7950X 16-Core Processor
GPU:
  Name:                    AMD Ryzen 9 7950X 16-Core Processor
  Marketing Name:          AMD Ryzen 9 7950X 16-Core Processor
  Name:                    gfx1100                            
  Marketing Name:                                             
      Name:                    amdgcn-amd-amdhsa--gfx1100
```

**Comment by kuhar** [comment]
BTW, rocm 6.1 is missing from your issue template.

**Comment by Naraenda** [comment]
`llvm-dis` can be found in the `rocm-llvm-dev` package which isn't installed by default. The proper fix is to modify the CMake script to detect whether `llvm-dis` is available, but for now just installing `rocm-llvm-dev` should resolve the issue.

**Comment by kuhar** [comment]
@Naraenda the cmake seems to be already checking for clang in the right location:
> `-- Check for working HIP compiler: /opt/rocm-6.1.0/llvm/bin/clang++ - skipped`

I think that a proper fix should search for llvm-dis in one of those rocm directories instead of relying on whatever llvm-dis is in the path being compatible with the rocm installation. I don't know where rocm-llvm-dev installs packages exactly, but it wouldn't be acceptable, IMO, to make it be the system-wide provider of llvm packages.

**Comment by Naraenda** [comment]
Actually `HIP-Basic/llvm_ir_to_executable/CMakeLists.txt` already searches for `llvm-dis` (and other required programs) in `${ROCM_ROOT}/llvm/bin` (where `ROCM_ROOT` is usually `/opt/rocm-x.y.z`). The error is because a top level build is trying to build the example instead of gracefully skipping.

In ROCm 6.1 the `rocm-llvm` package was split between basic compilation and development tools (`rocm-llvm-dev`), so installing both is the same as installing the first pre 6.1. `rocm-llvm-dev` doesn't come pre-bundled in most docker images/meta packages.

Apologies for not being clear and thorough the first time 😅
