### ISSUE TITLE
[Issue]: I don't know why different result in the rocm-examples/Applications/convolution/  

### ISSUE THREAD

**Issue by fortunerains** [amd/rocm-examples#120]
### Problem Description

In the example **（convolution）**，there were  two different results with make and cmake

![F19D0AD0-F2C7-4027-A3C1-C325B74BF03A](https://github.com/ROCm/rocm-examples/assets/24492495/794cb93f-05eb-4e60-a4df-4e7fb221564a)

![D17A0F5B-1767-47E3-A775-8FE811C07480](https://github.com/ROCm/rocm-examples/assets/24492495/f6068ed8-b84a-454b-aec3-9bae7818efcd)

Time-consuming is different！  why？

### Operating System

Linux td50 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### CPU

Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIP, HIPCC

### Steps to Reproduce

gpu 7700xt

**Comment by Naraenda** [comment]
Make uses `hipcc` which implicitely by default calls `clang++` with `-O3`. CMake uses `clang++` directly, so you need to pass `-DCMAKE_HIP_FLAGS=-O3` or set build type to release (with `-DCMAKE_BUILD_TYPE=Release`).

The following produces the same runtine as building with Make.
```sh-session
nara:examples/Applications/convolution/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
nara:examples/Applications/convolution/build$ cmake --build .
nara:examples/Applications/convolution/build$ ./applications_convolution
```
