### ISSUE TITLE
looking for an documentation what do after installation an hip and rocm if cant do anything afterward 

### ISSUE THREAD

**Issue by xalteropsx** [amd/rocm-examples#126]
### Suggestion Description

need good documentation how to utilized rocm in window 
the problem is user install these thing and don't have proper documentation to do what next lack of info 

### Operating System

window

**Comment by xalteropsx** [comment]
regarding this i need proper approach how u utilized hip or rocm in window in certain tool to proper understanding and good documentation must need all just provided an installation of hip wont help end user 

any using torch or is similar example in c# will be good so plz drop it link or comment so i can understand and create a proper program using it

**Comment by Naraenda** [comment]
As I explained in #123 this repository contains **C++** examples for ROCm. After installing ROCm 5.7 for Windows you should be able to run the 5.7 examples (i.e. https://github.com/ROCm/rocm-examples/tree/rocm-rel-5.7-staging-stream) by opening the Visual Studio solution file.

AFAIK ROCm 6.x isn't supported by Windows yet, only ROCm 5.7, so to use Torch, make sure you have a [compatible version](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/3rd-party-support-matrix.html#deep-learning).

**Comment by xalteropsx** [comment]
I do have 5.7 compatible GPU with hip on rx7900 but the process of compile torch is not clear and understandable 

I will try ur link and let u know feedback tomorrow  will see if cmake work or not without docker and wsl

**Comment by xalteropsx** [comment]
sorry for pretty late work seems like my visual studio remove last time when new window install will download and test later if face any issue i will reopen it but no plan to install visual studio for an month
