### ISSUE TITLE
[Feature]: support gfx902 and gfx90c

### ISSUE THREAD

**Issue by rainhenry** [amd/rocm-examples#145]
### Suggestion Description

Will it be possible to support gfx902 and gfx90c in the future? Do you have a table showing the correspondence between these device code and specific retail chip models?  For example, gfx902 is Ryzen 3 2200G.   gfx90c is Ryzen 7 5800U.

**Comment by Snektron** [comment]
> Will it be possible to support gfx902 and gfx90c in the future?

Perhaps, I've seen some commotion on the LLVM repository about adding support for a 'generic' HIP target that is not GPU-specific. I don't know a lot about it, though. For now our focus is still on the GPUs that are officially enabled for ROCm by AMD (see [here](https://rocm.docs.amd.com/en/latest/reference/gpu-arch-specs.html)). If you have any specific issue with those GPUs you mentioned, I don't mind investigating a fix. I've personally had mixed results with gfx90c and I've heard about issues with APUs in general. It seems that a decent portion of rocPRIM tests does actually work on my own gfx90c, but i haven't tested the examples yet. Of course, some pre-compiled libraries like rocBLAS etc will not work as they will not have those APU targets enabled by default. In theory the HIP-Basic, rocPRIM and hipCUB examples should work fine.

> Do you have a table showing the correspondence between these device code and specific retail chip models? For example, gfx902 is Ryzen 3 2200G. gfx90c is Ryzen 7 5800U.

The only such list I know of for non-ROCm supported GPUs is in the LLVM documentation: https://llvm.org/docs/AMDGPUUsage.html#processors
