### ISSUE TITLE
Additional GPU targets

### ISSUE THREAD

**Issue by saadrahim** [amd/rocm-examples#17]
Please add support for add support for gfx1100, gfx1101 and gfx1102.

Please guard the selection of the architecture with rocm_check_target_ids. I am a little wary of adding another dependency to this project, so you may want to copy the code to this repo.

**Comment by Snektron** [comment]
> Please guard the selection of the architecture with rocm_check_target_ids

As it stands, both the CMake and Makefiles automatically detects which architecture(s) the user has, and compiles for those targets exactly. For CMake, this is also documented on [CMAKE_HIP_ARCHITECTURES](https://cmake.org/cmake/help/latest/variable/CMAKE_HIP_ARCHITECTURES.html). As there are no binary releases for the examples (at least currently), and the user is expected to compile them on their own accord anyway, Im not sure that it is necessary to hardcode the list of supported targets, or to compile examples for targets that the user does not have anyway. This also allows us to keep the CMake file for the examples self contained, as we do not need to introduce this check for every example.
