### ISSUE TITLE
[Issue]: Rocm-smi does not work when building container from the dockerfile hip-libraries-rocm-ubuntu.Dockerfile

### ISSUE THREAD

**Issue by umechand-amd** [amd/rocm-examples#171]
### Problem Description

Rocm-smi doesnt work when using the container from the Dockerfile  _hip-libraries-rocm-ubuntu.Dockerfile_
developer@gpuperf-lab-78:/workspaces$ rocm-smi
bash: rocm-smi: command not found
OS:
NAME="Ubuntu"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
CPU: 
model name      : AMD EPYC 9554 64-Core Processor
GPU:

### Operating System

Ubuntu 22.04.4 LTS

### CPU

AMD EPYC 9554 64-Core Processor

### GPU

AMD Instinct MI300X, AMD Instinct MI300A

### ROCm Version

ROCm 6.2.0

**Comment by dgaliffiAMD** [comment]
Hi @umechand-amd , 
I believe the docker files are limited to include only the components required to run the examples. This is to reduce the overall size of the image. 
Can you include details on which example is failing in your setup? 
Thank you.

**Comment by umechand-amd** [comment]
I dont even to get to build because the container cannot find GPUs.

**Comment by dgaliffiAMD** [comment]
Thanks for the addition details. We're trying to reproduce in-house. 
You should be able to _build_ without GPUs. That's what we do in our GitHub workflows. But, I understand, you won't be able to run.

**Comment by Beanavil** [comment]
Seems like `rocm-smi-lib` is missing from the install step of the dockerfile. I think as an immediate fix you can install it from within the container:
```bash
sudo apt-get install rocm-smi-lib
```
or add it to your local dockerfile:
```diff
# Install the HIP compiler and libraries from the ROCm repositories
RUN export DEBIAN_FRONTEND=noninteractive; \
    mkdir -p /etc/apt/keyrings \
    && wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | gpg --dearmor > /etc/apt/keyrings/rocm.gpg \
    && echo "deb [arch=amd64, signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/$ROCM_VERSION_APT/ jammy main" > /etc/apt/sources.list.d/rocm.list \
    && printf 'Package: *\nPin: origin "repo.radeon.com"\nPin-Priority: 9001\n' > /etc/apt/preferences.d/radeon.pref \
    && apt-get update -qq \
    && apt-get install --no-install-recommends -y \
-       hip-base hipify-clang rocm-core hipcc \
+       hip-base hipify-clang rocm-core hipcc rocm-smi-lib \
        hip-dev rocm-hip-runtime-dev rocm-llvm-dev \
        rocrand-dev hiprand-dev \
        rocprim-dev hipcub-dev \
        rocblas-dev hipblas-dev \
        rocsolver-dev hipsolver-dev \
        rocfft-dev hipfft-dev \
        rocsparse-dev \
        rocthrust-dev \
    && rm -rf /var/lib/apt/lists/*
```
At least that works on my end

**Comment by harkgill-amd** [comment]
Confirmed with user internally, issue was related to lack of GPU access within docker container. After running container with GPU access, rocm-examples were built and ran successfully. https://github.com/ROCm/rocm-examples/commit/cfbca5428e4b7ee8abde583073fe1351fdf24d5c addresses the root cause of this issue.
