### ISSUE TITLE
Prerelease Info

### ISSUE THREAD

**Issue by ev-dev** [amd/rocm-examples#33]
Hey AMD devs!

I keep stumbling upon more and more hints of upcoming rocm/hip releases and I just sincerely wanted to thank all of you for the hard work being done to bring support to Windows. 

I have been periodically digging thru forums & dark corners of strange github repos, for what has literally been _years_ at this point, to try and find any indication of a future for rocm on windows. Despite lots of negativity out there around the topic, I'm excited for what's to come 🚀

Any rough timeline for when any initial previews of the hip/rocm sdks for windows might be accessed publically?

**Comment by Snektron** [comment]
this is a secret 🤐

**Comment by emankov** [comment]
HIP SDK 5.5 for Windows was released in Jul 2023
HIP SDK 5.7 for Windows was released in Jan 2024
Both are available globally: https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
