### ISSUE TITLE
How to get access to example?

### ISSUE THREAD

**Issue by yhyu13** [amd/rocm-examples#44]
Hi,

Maybe a stupid question, it seems I don't have access to https://github.com/Applications/floyd_warshall/ (which presents here https://github.com/amd/rocm-examples/blob/develop/README.md)with 404 error. 

Is it a private repo? How do I join the deverloper orgnization in order to get access to examples shown here https://github.com/amd/rocm-examples/blob/develop/README.md

**Comment by LucasSnatiago** [comment]
I think the only problem is the link you've used. All links available in the readme are broken #15, the real one is https://github.com/amd/rocm-examples/tree/develop/Applications/floyd_warshall . It should work.
