### ISSUE TITLE
How to run rocm examples

### ISSUE THREAD

**Issue by Bear-Beer** [amd/rocm-examples#47]
after compiling with make commandline successfully with the source code.  the new problem is how to run the examples.

for example, ran applications_floyd_warshall in Applications/floyd_warshall directory, I got this:
[root@localhost floyd_warshall]# ./applications_floyd_warshall
Executing Floyd-Warshall algorithm for 1 iterations with a complete graph of 16 nodes.
The mean time needed for each iteration has been 0.704048ms.
Validating results with **CPU** implementation.
Validation passed.
[root@localhost floyd_warshall]#

How can I run it against my GPU - RX6700

**Comment by Naraenda** [comment]
> Validating results with CPU implementation.

The algorithm still runs on the GPU, it's validating the results from the GPU computation with an implementation that runs on CPU. If you run the program with a higher iteration the process should show up in `rocm-smi --showpidgpus --showpids`:
```bash
watch -n 1 rocm-smi --showpidgpus --showpids
```
And running Floyd-Warshall with, for example:
```bash
applications_floyd_warshall -i 1024 -n 1024
```

**Comment by Naraenda** [comment]
Closing it since it's stale. Please reopen it or make a new issue if you have any more problems.
