### ISSUE TITLE
Run applications_convolution failed with AMD Radeon Pro W7900

### ISSUE THREAD

**Issue by alexhegit** [amd/rocm-examples#57]
I compile the git repo with "make" and the compiling finished without any error. Then I try to run some application like /rocm-examples/Applications/convolution/applications_convolution, but got failed. 

root@AIG-PM:/home/rocm-examples/Applications/convolution# ./applications_convolution
Executing a simple convolution for 10 iterations with a 4096 x 4096 sized grid.
An error encountered: "invalid kernel file" at main.hip:242

I read the documents of this git. And just guest the compile should set the LLVM target of W7900 which is gfx1036. But I did not find out how to do the compile with gfx1036 as the LLVM target. Or may be other reason of the failed run.

**Comment by Snektron** [comment]
The LLVM target of the W7900 should be gfx1100. You can configure this by adding [`-DCMAKE_HIP_ARCHITECTURES=gfx1100`](https://cmake.org/cmake/help/latest/variable/CMAKE_HIP_ARCHITECTURES.html) to the command when compiling with cmake, though by default both cmake and make should attempt to figure it out by themself. Can you post your build command and it's full output using make, and also try with cmake?

**Comment by alexhegit** [comment]
Fixed now. Thank you. @Snektron
