### ISSUE TITLE
build failed with Vulkan_GLSLANG_VALIDATOR_EXECUTABLE-NOTFOUND

### ISSUE THREAD

**Issue by alexhegit** [amd/rocm-examples#63]
I got the build failed log as bellow: 

[ 40%] Compiling vertex shader
/bin/sh: 1: Vulkan_GLSLANG_VALIDATOR_EXECUTABLE-NOTFOUND: not found
gmake[2]: *** [HIP-Basic/vulkan_interop/CMakeFiles/shaders.dir/build.make:78: HIP-Basic/vulkan_interop/sinewave.vert.spv.h] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:2697: HIP-Basic/vulkan_interop/CMakeFiles/shaders.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
(base) amd@AIG-PM:~/Gits/rocm-examples$

How to fix it?

**Comment by alexhegit** [comment]
I try to install the package of vulkan-*, glslang-dev but still got same failed.

**Comment by Snektron** [comment]
Its provided by `glslang-tools`
```
$ apt-file find glslangValidator
[... output truncated]
glslang-tools: /usr/bin/glslangValidator  
```

**Comment by Naraenda** [comment]
I assume the above fixed it. Please reopen if there's still a problem.
