### ISSUE TITLE
not found \vs2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\x64\PlatformToolsets\HIP clang 5.7\AMD.HIP.Clang.Common.props

### ISSUE THREAD

**Issue by yanite** [amd/rocm-examples#85]
where HIP clang 5.7 ?

**Comment by emankov** [comment]
Hello @yanite,

We will let you know once HIP SDK 5.7 is finally released.  For now, please use rocm-examples based on https://github.com/amd/rocm-examples/pull/64 with HIP SDK 5.5.

Thanks,
Evgeny

**Comment by emankov** [comment]
Hello @yanite,

[HIP SDK 5.7](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) has been released. Please, install it to use rocm-examples.
