### ISSUE TITLE
README Documentation Link is wrong

### ISSUE THREAD

**Issue by Samiii777** [amd/rocm-examples#94]
The link to the AI section should be corrected in here: https://github.com/amd/rocm-examples/blob/develop/README.md
from: https://github.com/rocm-examples/tree/develop/AI/MIGraphX/Quantization
to: https://github.com/amd/rocm-examples/tree/develop/AI/MIGraphX/Quantization

**Comment by Naraenda** [comment]
Thank you for the report, I've made an PR (#107) that'll fix it.
